name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: linux-cpu-large
    container:
      image: node:18
      env:
        NODE_ENV: development
      ports:
        - 80
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

